spring.application.name=cowork
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cowork_db}
spring.datasource.username=${DB_USERNAME:user_db}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:change-this-secret-key-change-this-secret-key}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}
app.payment.mercadopago.access-token=${MP_ACCESS_TOKEN:test-token}
app.payment.mercadopago.webhook-secret=${MP_WEBHOOK_SECRET:test-webhook-secret}
